### PR TITLE
basic useragent detection for suggesting correct download option

### PR DESCRIPTION
**Pull request by norgeous**
hello,

Decided to start from scratch building a custom js useragent detector, rather than using a (potentially) bulky library with not needed features.

I have included some example useragent strings that I found on google and some development notes in `useragent.js`.

I am not a software developer, so I don't have much clue with regards to which systems are 32 or 64. hopefully what I have written under `BIT NOTES` is correct as this is what I'm basing the detection code on...

I'm not sure how to test the code fully, who has access to all these OS'?

I will try testing with http://browsershots.org/ shortly, but it's not comprehensive.
Will provide the link once the screen grabs are in...

### CODE REVIEW

**Comment by norgeous** [comment]
#6

**Comment by norgeous** [comment]
http://browsershots.org/http://lab.danielharte.co.uk/syncthingdl/index.static.html

**Comment by norgeous** [comment]
screenshot- domain date time

**Comment by norgeous** [comment]
have the code working 99% accurate as far as I can tell, green box highlight as shown above. Separated the testing grounds out into it's own file. can someone test this?

**Comment by calmh** [comment]
Looks like a good start. I think we should have the server side add suitable attributes to generated HTML, so that we don't need to match too specifically in the javascript. That is, a download could be

``` html
<a class="os-windows arch-amd64" href="...">Syncthing for Windows (64 bit)</a>
```

and the Javascript could push suitable CSS rules to highlight all things `.os-windows.arch-amd64` if that is what is detected, and this would highlight all the various downloads that are compatible?

**Comment by norgeous** [comment]
`a:contains()` css selector selects all links that contain a certain piece of text.
In the last commit I modified the the input to this from `Syncthing for Windows (64 bit)` (or varients) to just `Windows (64 bit)`. Now it matches all the trayzor/gtk/disco/etc, no serverside needed.

**Comment by norgeous** [comment]
now it looks like:
screenshot-localhost 8891 2016-03-30 23-39-44

**Comment by norgeous** [comment]
i think this is a far as i will take this pr.
fixes #6 at least (might be buggy for edge case tho)

**Comment by norgeous** [comment]
also fixes #8 and #9

**Comment by calmh** [comment]
Thanks. I'm not so sure about the IsSyncthing parts and so on, but we can tweak that as we go along.

**Comment by calmh** [comment]
@st-review merge this please

Basic user agent detection, extra references in HTML (fixes #6, fixes #8, fixes #9)

**Comment by st-review** [comment]
OK, merged as 0efc4d16aca4f757b88d94d5c70f8ad3fe254a04. Thanks, @norgeous!

**Pull request closed without merging**
